name: Update Packages

on:
  workflow_dispatch:
  schedule:
    # UTC 21:00 -> CST (China) 5:00
    - cron: '0 21 * * 3'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Install npm-check-updates
        run: npm install -g npm-check-updates

      - uses: actions/checkout@v4

      - name: Update packages
        run: ncu -u

      - name: Set time zone
        run: |
          sudo timedatectl set-timezone 'Asia/Shanghai'
          echo "CURRENT_DATE=$(date '+%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV
      
      - name: Generate timestamp SVG
        run: |
          echo '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="226" height="20" role="img" aria-label="last check: ${{ env.CURRENT_DATE }}+08:00"><title>last check: ${{ env.CURRENT_DATE }}+08:00</title><linearGradient id="s" x2="0" y2="100%"><stop offset="0" stop-color="#bbb" stop-opacity=".1"/><stop offset="1" stop-opacity=".1"/></linearGradient><clipPath id="r"><rect width="226" height="20" rx="3" fill="#fff"/></clipPath><g clip-path="url(#r)"><rect width="53" height="20" fill="#555"/><rect x="53" width="173" height="20" fill="#4c1"/><rect width="226" height="20" fill="url(#s)"/></g><g fill="#fff" text-anchor="middle" font-family="Verdana,Geneva,DejaVu Sans,sans-serif" text-rendering="geometricPrecision" font-size="110"><text aria-hidden="true" x="275" y="150" fill="#010101" fill-opacity=".3" transform="scale(.1)" textLength="430">last check</text><text x="275" y="140" transform="scale(.1)" fill="#fff" textLength="430">last check</text><text aria-hidden="true" x="1385" y="150" fill="#010101" fill-opacity=".3" transform="scale(.1)" textLength="1630">${{ env.CURRENT_DATE }}+08:00</text><text x="1385" y="140" transform="scale(.1)" fill="#fff" textLength="1630">${{ env.CURRENT_DATE }}+08:00</text></g></svg>' >> timestamp.svg

      - name: Commit changes
        uses: EndBug/add-and-commit@main
        with:
          author_name: github-actions
          author_email: github-actions[bot]@users.noreply.github.com
          message: 'chore: check update'
          add: '.'
